# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "main" # The branch the pull request should be targeted at
    rebase-strategy: disabled # The rebase strategy to use when rebasing pull requests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    rebase-strategy: disabled
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/"
    target-branch: "main"
    rebase-strategy: disabled
    schedule:
      interval: "weekly"
