services:
  telegram-db:
    image: pgvector/pgvector:0.8.0-pg15
    container_name: telegram-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_V_USER}
      POSTGRES_PASSWORD: ${POSTGRES_V_PASSWORD}
      POSTGRES_DB: ${POSTGRES_V_DB}
    volumes:
      - ./telegram-db:/var/lib/postgresql/data
